# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup gcloud environment
      uses: GoogleCloudPlatform/github-actions@0.1.2
      with:
        # The service account email which will be used for authentication.
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        # The service account key which will be used for authentication.
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        
    - name: Deploy wateringCan
      run: gcloud functions deploy wateringCan --project ${{ secrets.GCP_PROJECT_ID }} --runtime nodejs8 --trigger-http --allow-unauthenticated
